
<main class="main-container">
    <nav class="links-rapidos">
        <ul>
            <li>
                <a href="/emprestimo">
                    <img class="bib-icon" src="img/emprestimo.png" alt="emprestimo">
                    <p>Empréstimo</p>
                </a>
            </li>
            <li>
                <a href="/devolucao">
                    <img class="bib-icon" src="img/devolucao.png" alt="devolucao">
                    <p>Devolução</p>
                </a>
            </li>
            <li>
                <a href="/buscar_livro">
                    <img class="bib-icon" src="img/busca.png" alt="busca">
                    <p>Buscar<br />Título</p>
                </a>
            </li>
        </ul>
    </nav>
</main>
