
<div class="container-login">
    <div class="login">
        <img src="img/library-logo.svg" alt="logo-biblioteca" id="logo-login">
        <form action="/autenticar" method="POST">
            <label for="usuario">Usuário</label>
            <input type="text" name="usuario" id="usuario">
            <label for="senha">Senha</label>
            <input type="password" name="senha" id="senha">
            <input type="submit" value="Acessar">
        </form>
        <a href="" id="redefinir-senha">Esqueceu a senha?</a>
    </div>
</div>
