<?= $this->toString($_SESSION) ?>
<main id="buscar-livro" class="main-container">
    <div class="main-content">

        <div class="group-title">
            <h1>Buscar Livro</h1>
        </div>

        <form action="<?= $_SERVER["REQUEST_URI"] ?>" method="post">
            <div id="radio-opcoes-busca">
                <p>Buscar por:</p>
                <div>
                    <input type="radio" name="radio-busca" id="radio-busca-codigo" value="código" checked>Código
                </div>
                <div>
                    <input type="radio" name="radio-busca" id="radio-busca-titulo" value="título">Título
                </div>
            </div>
            <div id="input-busca" class="input-group">
                <input type="search" name="busca-livro" id="busca-livro" placeholder="Buscar por código">
                <button id="bib-button-buscar" class="bib-button bib-button-secundary">Buscar</button>
            </div>

            <?php
            if (isset($_POST["busca-livro"])) {
                $infoLivro = $this->view->dados;

                if (isset($_GET['emprestimo'])) {

                    $_SESSION['novo_emprestimo']['livro'] = $infoLivro;
                }

                if (empty($infoLivro)) {
                    $this->erro('Livro não encontrado');
                } else {

            ?>
                    <div id="info-livro">
                        <p><strong>Título: </strong><?= $infoLivro['titulo'] ?></p>
                        <p><strong>Autor: </strong><?= $infoLivro['autor'] ?></p>
                        <p><strong>Editora: </strong><?= $infoLivro['editora'] ?></p>
                        <p><strong>Ano de publicação: </strong><?= $infoLivro['ano_publicacao'] ?></p>
                    </div>

            <?php
                    if ($infoLivro['exemplares_disponiveis'] == 0) {
                        $this->erro('Não há exemplares disponíveis para este livro.');
                    }
                }
            }
            ?>

            <?php if (isset($_GET['emprestimo'])): ?>
                <div class="button-group">
                    <button type="button" id="bib-button-cancelar" class="bib-button bib-button-cancel">Cancelar</button>
                    <button type="button" id="adicionar-livro" class="bib-button bib-button-primary">Adicionar</button>
                </div>
            <?php endif; ?>
        </form>
    </div>
</main>

<script>
    let radio = document.getElementsByName('radio-busca');

    radio.forEach(radio => {
        radio.addEventListener('click', () => {

            document.getElementById('busca-livro').placeholder = 'Buscar por ' + radio.value
        })
    });

    <?php if (isset($_GET['emprestimo'])): ?>
        let $numEmprestimo = <?= $_GET['emprestimo'] ?>

        function voltarEmprestimo($numEmprestimo) {
            return `/emprestimo?emprestimo=${$numEmprestimo}`
        }

        document.getElementById('bib-button-cancelar').addEventListener('click', () => {

            document.location.href = voltarEmprestimo($numEmprestimo)

        })
        <?php if (isset($_POST["busca-livro"])): ?>
            document.getElementById('adicionar-livro').addEventListener('click', () => {
                document.location.href = voltarEmprestimo($numEmprestimo)

            })
        <?php endif; ?>
    <?php endif; ?>
</script>