<?php
    $listaUsuarios = $this->view->dados;
?>
<main id="emprestimo" class="main-container">
    <div class="main-content">
        <div class="group-title">
            <img class="bib-icon" src="img/emprestimo.png" alt="emprestimo">
            <h1>Novo Empréstimo</h1>
        </div>
        <form method="post" action="/buscar_livro">
            <div class="input-group">
                <label for="select-usuario">Usuário:</label>
                <select name="select-usuario" id="select-usuario">
                    <option disabled selected value="null">Selecione um usuario</option>
                    <?php foreach ($listaUsuarios as $usuario): ?>
                        <option value="<?= $usuario->nome ?>"><?= $usuario->nome ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <?php
            if (isset($_GET['erro']) && $_GET['erro'] = 1) {
                $this->erro('Selecione um usúario para realizar o emprestimo');
            }
            ?>

            <input type="submit" id="incluir-titulo" class="bib-button bib-button-secundary" value="Incluir Título"></input>

            <button type="submit" id="concluir" class="bib-button bib-button-primary">Concluir</button>
        </form>
    </div>
</main>
<script>
    document.getElementById('incluir-titulo').addEventListener('click', () => {
        let usuario = document.getElementById('select-usuario').value;
        if (usuario == 'null') {
            document.location.href = '/emprestimo?erro=1'
        }
    })

</script>