<?php
$listaUsuarios = $this->view->dados;
$this->toString($_SESSION);

if (!isset($_GET['emprestimo'])) {
    unset($_SESSION['novo_emprestimo']);
    $num_emprestimo = rand();
} else {
    $num_emprestimo = $_SESSION['novo_emprestimo']['num_emprestimo'];
}
?>
<main id="emprestimo" class="main-container">
    <div class="main-content">
        <div class="group-title">
            <img class="bib-icon" src="img/emprestimo.png" alt="emprestimo">
            <h1>Novo Empréstimo</h1>
        </div>
        <form method="post" action="/novo_emprestimo">
            <div class="input-group">
                <label for="select-usuario">Usuário:</label>
                <select name="select-usuario" id="select-usuario">
                    <option disabled selected value="null">Selecione um usuario</option>
                    <?php foreach ($listaUsuarios as $usuario): ?>
                        <?php if(isset($_GET['emprestimo']) && $usuario->nome == $_SESSION['novo_emprestimo']['usuario'] && $_GET['emprestimo'] == $_SESSION['novo_emprestimo']['num_emprestimo']):?>
                        <option selected value="<?= $usuario->nome ?>"><?= $usuario->nome ?></option>
                        <?php endif;?>
                        <option value="<?= $usuario->nome ?>"><?= $usuario->nome ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <?php
            if (isset($_GET['erro'])) {
                switch($_GET['erro']){
                    case 1:
                        $this->erro('Selecione um usúario para realizar o emprestimo');
                        break;
                    case 2:
                        $this->erro('Não foi possível concluir o empréstimo');
                        break;
                }
            }
            ?>

            <?php if (isset($_GET['emprestimo']) && $_GET['emprestimo'] == $_SESSION['novo_emprestimo']['num_emprestimo'] && isset($_SESSION['novo_emprestimo']['livro'])): ?>
                <div id="info-livro">
                    <p><strong>Título: </strong><?= $_SESSION['novo_emprestimo']['livro']['titulo'] ?></p>
                    <p><strong>Autor: </strong><?= $_SESSION['novo_emprestimo']['livro']['autor'] ?></p>
                    <p><strong>Editora: </strong><?= $_SESSION['novo_emprestimo']['livro']['editora'] ?></p>
                    <p><strong>Ano de publicação: </strong><?= $_SESSION['novo_emprestimo']['livro']['ano_publicacao'] ?></p>
                </div>

            <?php endif; ?>

            <input type="button" id="incluir-titulo" class="bib-button bib-button-secundary" value="Incluir Título"></input>

            <button type="submit" id="concluir" class="bib-button bib-button-primary">Concluir</button>
        </form>
    </div>
</main>
<script>
    document.getElementById('incluir-titulo').addEventListener('click', () => {
        let usuario = document.getElementById('select-usuario').value;
        if (usuario == 'null') {
            document.location.href = '/emprestimo?erro=1'
        } else {
            document.location.href = '/buscar_livro?usuario=' + usuario + '&emprestimo=<?= $num_emprestimo ?>'
        }

        console.log(usuario)

    })
</script>